### ISSUE TITLE
SPA route changes not being tracked

### ISSUE THREAD

**Issue by michaviehauser** [derrickreimer/fathom-client#11]
I am using this package with NextJs hosted on Vercel, have implemented the tracking code as shown on the bottom of the  README file, and notice the following:
- Opening up ANY route on the page counts as a hit for the ROOT page (/)
- Navigating the site NEVER shows page visits other than the ROOT page in the Dashboard

To fix this, I have played with different kind of config settings (spa, ...) and also the slightly different way proposed directly by Vercel in their official Fathom guide: https://vercel.com/guides/deploying-nextjs-using-fathom-analytics-with-vercel

Has anyone experienced this kind of behavior before?

**Comment by derrickreimer** [comment]
Hi @michaviehauser I'm having trouble reproducing this. One of my products is a Next.js app and I'm using the config from the README. I navigated directly to my `/pricing` page and then clicked an internal link to the `/docs` page, and this is what the request log is showing:

<img width="1118" alt="Pasted_Image_9_14_20__4_06_PM" src="https://user-images.githubusercontent.com/341387/93138192-37d50c00-f6a4-11ea-85d3-bfcb33b30a2e.png">

Is your repo public, or can you paste the relevant snippet here from your app?

**Comment by michaviehauser** [comment]
@derrickreimer I mirrored the scenario you'd described and this is what it looks on my end:
![Screenshot 2020-09-14 at 11 33 18 PM](https://user-images.githubusercontent.com/39144548/93140787-53133c00-f6e3-11ea-97f6-1f17aa1ff49f.png)

Not sure if the encoded URL has something to do with it, but it certainly only shows the encoded root path %2F on both calls for the "p" query param.

This is the implementation part:
![Screenshot 2020-09-14 at 11 41 28 PM](https://user-images.githubusercontent.com/39144548/93141728-03357480-f6e5-11ea-9596-1d1a6cf0e2f4.png)

Additionally, I have tried disabling all kinds of service workers that could interfere but with the same result.

**Comment by derrickreimer** [comment]
Do you have a `<link rel="canonical" ...>` tag in your `<head>` set to `/`, by chance? This will override what's in the window location unless you set `canonical` to `false` in your load call:

```js
Fathom.load(id, {
  canonical: false,
  // rest...
})
```

**Comment by michaviehauser** [comment]
Correct guess! There was a badly placed canonical tag within the <head> that I removed.

Thank you so much for helping out @derrickreimer !

**Comment by derrickreimer** [comment]
Awesome! Glad to help. I've run into weirdness with canonical tags myself before 😅

**Comment by michaviehauser** [comment]
They are the worst! (at least when you don't need them)
