### ISSUE TITLE
New "custom domains" option

### ISSUE THREAD

**Issue by bjufre** [derrickreimer/fathom-client#25]
Hello, after the big update announcement for the new functionality like "custom domains" for a script to allow avoiding 3rd party ad blockers to take affect with fathom script, is this library going to be updated to allow for such settings?
We've already updated the script settings for our case, but the live site still uses the "old cdn domain".

Thank you!

**Comment by bjufre** [comment]
Never mind I saw the `url` option! 💪

**Comment by derrickreimer** [comment]
👍
