### ISSUE TITLE
NextJS React Hook

### ISSUE THREAD

**Issue by joshmedeski** [derrickreimer/fathom-client#26]
I recently found a clean way to add Fathom to a NextJS app:
https://www.joshmedeski.com/how-to-install-fathom-analytics-in-nextjs

Could this code be added to this project? If you want to keep it unopinionated from frameworks, I understand.

If so, I can add it and the implementation would look like this:

```ts
import React from "react";
import type { AppProps } from "next/app";
import useNextJsFathomAnalytics from "fathom-client";

const App: React.FC<AppProps> = ({ Component, pageProps }) => {
  useNextJsFathomAnalytics();

  return <Component {...pageProps} />
};

export default App;
```

I'd include documentation for what environmental variables are being used.

Furthermore, I plan on reach out to the Fathom team and have them update their documentation if we add this hook. https://usefathom.com/docs/integrations/next

**Comment by derrickreimer** [comment]
Hey Josh! I think we do want to keep this library framework-agnostic. I wonder if utilizing environment vars is unnecessary for most use cases -- assuming that people usually just want to track metrics in production, so a static `includedDomains` allowlist + a static site ID will suffice. 

What I like about having the implementor use their own `useEffect` hook is that it hopefully makes it very clear what's happening at various points in the page lifecycle, and a gives them easy extensibility (e.g. you could also add a `trackGoal` call there under some specific condition if you wanted to):

```js
import React, { useEffect } from 'react';
import Router from 'next/router';
import * as Fathom from 'fathom-client';

// Record a pageview when route changes
Router.events.on('routeChangeComplete', () => {
  Fathom.trackPageview();
});

function App({ Component, pageProps }) {
  // Initialize Fathom when the app loads
  useEffect(() => {
    Fathom.load('MY_FATHOM_ID', {
      includedDomains: ['yourwebsite.com']
    });
  }, []);

  return <Component {...pageProps} />;
}

export default App;
```

(Pulled from https://github.com/derrickreimer/fathom-client#nextjs)

I could definitely see adding an additional example that makes use of Next env vars though! What do you think?

**Comment by joshmedeski** [comment]
I realize the env vars are public, so it's unnecessary to put them in version control. But I prefer third party data to be left out of version control.

I created a hook because I also like having `_app.jsx` as clean as possible 😉 

And I totally get not including a custom NextJS hook in the project. Feel free to take anything from my article and add it to the README.

p.s. SavvyCal is amazing! I'm a big fan.
