### ISSUE TITLE
CORS error with custom domain

### ISSUE THREAD

**Issue by dmitrizzle** [derrickreimer/fathom-client#35]
I'm seeing CORS error when browsing to the next page. Strangely, the CORS comes from a duplicate request (but from my WebPack chunk rather than from Fathom's script -- see attached). 

I checked my dashboard and I'm seeing my session being shown so there're no issues with functionality as far as I know.

I'm using a custom domain and I use `Fathom.trackPageview();` on route changes pretty much exactly how it appears in the docs.

**Comment by derrickreimer** [comment]
Hey @dmitrizzle -- you mentioned "see attached" -- is there a missing attachment here with a bit more info?

**Comment by dmitrizzle** [comment]
Ah yes, sorry!
![Screen Shot 2022-06-10 at 1 28 00 PM](https://user-images.githubusercontent.com/8587882/173714929-89ee0673-1aeb-478f-9b80-6f6c5218554f.png)

BUT I can no longer replicate this error. I'm not sure what I did to make it go away, could be something as convoluted as caching from my previous setup...

**Comment by derrickreimer** [comment]
Hmm strange. CORS is always a bit of a nightmare. Going to close for now, since I don't think this is directly related to this library.
