### ISSUE TITLE
Event tracking not working

### ISSUE THREAD

**Issue by cicixxue** [derrickreimer/fathom-client#37]
Hi I followed the instruction in inserting `Fathom.trackGoal('EventCode', 0);` in my event handler 
but after deploying into prod, Fathom was not able to showing any event captured for that eventCode. 
I put the `Fathom.trackGoal('EventCode', 0);` just before my `return` statement in my async function. 
```
export default async functions* myfunction({parameters}): mytypes {
......
Fathom.trackGoal('EventCode', 0);
return {values}
```
Any idea what could went wrong here?

**Comment by derrickreimer** [comment]
Hmm couple ideas:

- Are you calling [`load`](https://github.com/derrickreimer/fathom-client#loadsiteid-string-opts-object)?
- Is this function getting called right before a page navigation occurs? (It's possible there's a race condition where the call does not finish before the browser navigates)
- Are you using the right code? (You'll want to use the "Event ID" from the Fathom interface, not the name of the event)

<img width="699" alt="image" src="https://user-images.githubusercontent.com/341387/180840261-72e19181-9ce8-4edc-a6bd-098e872432f6.png">

Going to close this ticket, but if these don't work it's probably worth reaching out to Fathom support!
