### ISSUE TITLE
Next.js 13 (experimental appDir version): Fix to preserve server-side rendering

### ISSUE THREAD

**Issue by briangershon** [derrickreimer/fathom-client#44]
Greetings!

## Issue

I noticed my Next.js 13 app wasn't pre-rendering server-side meta tags in `<head />` -- and instead was loading client-side.

I tracked this down to the example Next.js 13 Fathom code in [README](https://github.com/derrickreimer/fathom-client/blob/master/README.md#nextjs)

## Solution

If you use the `useSearchParams` hook, NextJS will not pre-render the server component and instead the whole layout becomes client side.

I removed `useSearchParams` hook from the example, and that fixed my issue -- I was able to see a fully static-rendered page.

## Alternative solution

It's possible this behavior is a bug in Next.js 13 as well.

## Additional Info

I saw this in the beta Next.js 13 docs:

"During [static rendering](https://beta.nextjs.org/docs/rendering/fundamentals#static-rendering), any component using the useSearchParams hook will skip the prerendering step and instead be rendered on the client at runtime."

from: https://beta.nextjs.org/docs/api-reference/use-search-params

**Comment by briangershon** [comment]
This may be a regression in latest Next.js 13 -- I found a related issue: https://github.com/vercel/next.js/issues/45032#issuecomment-1402604265

**Comment by briangershon** [comment]
I just confirmed that if I do add `export const dynamic = 'force-dynamic'` (as mentioned in related issue link) to my `page.tsx`, the original example Fathom code works fine -- so maybe that's the workaround for now -- mentioning this is README as potential gotcha atm.

**Comment by briangershon** [comment]
A bit more info:

I noticed issue on stable Next.js `13.1.6` using `head.tsx` approach.

Then upgraded to `13.1.7-canary.10` to get the new upcoming [metadata features](https://beta.nextjs.org/docs/api-reference/metadata#title-templates) (which soon replaces `head.tsx` files in v13.2) and issue persisted.

**Comment by derrickreimer** [comment]
Hey thanks @briangershon! Not sure when I'll have a moment to dig into this, but I've added a note to the readme about compatibility (https://github.com/derrickreimer/fathom-client/commit/fa66d5708efb9b5ab3887c82778fc80a395035d8). Definitely welcome a PR based on a tested methodology! I am curious if there will be an officially documented method for hooking into the page lifecycle as this experimental stuff gets ironed out.

**Comment by briangershon** [comment]
You're welcome! Thanks for adding note in README so people have a work-around if they run into this.

Yeah, I'd just say let's wait a bit for things to shake out with `appDir` and see what happens.

**Comment by timneutkens** [comment]
Posted a reply here: https://github.com/vercel/next.js/issues/45032#issuecomment-1436623497

Changing the documented recommendation to this solves the issue:

```jsx
// Fathom.tsx
'use client'

import { load, trackPageview } from 'fathom-client'
import { useEffect, Suspense } from 'react'
import { usePathname, useSearchParams } from 'next/navigation'

function TrackPageView() {
  const pathname = usePathname()
  const searchParams = useSearchParams()
  useEffect(() => {
    load('MY_FATHOM_ID', {
      includedDomains: ['yourwebsite.com']
    })
  }, [])
  
  useEffect(() => {
    trackPageview()

    // Record a pageview when route changes
  }, [pathname, searchParams])

  return null
}

export default function Fathom() {
   return <Suspense fallback={null}>
      <TrackPageView />
   </Suspense>
}

```

**Comment by derrickreimer** [comment]
Thanks @timneutkens! 🎉

**Comment by briangershon** [comment]
Thanks @timneutkens

I just tried the new code and my server rendering stopped working, even with `<Suspense />`.

Also in my `page.tsx` I tried both with `export const dynamic = 'force-dynamic';` (the previous workaround) and without -- and didn't see server rendering.

I tested via `curl localhost:3000` -- in the workaround I see my `<head>` tags pre-rendered server side. In this version I don't.

Here are the changes I made:

```diff
diff --git a/app/page.tsx b/app/page.tsx
index bdf9a50..6ea44d5 100644
--- a/app/page.tsx
+++ b/app/page.tsx
@@ -13,7 +13,7 @@ import type { Metadata } from 'next';
 import { ExternalLink } from '@/components/ExternalLink';
 import Link from 'next/link';
 
-export const dynamic = 'force-dynamic';
+// export const dynamic = 'force-dynamic';
 
diff --git a/components/Fathom.tsx b/components/Fathom.tsx
index 1ee6704..f6ec023 100644
--- a/components/Fathom.tsx
+++ b/components/Fathom.tsx
@@ -1,10 +1,10 @@
 'use client';
 
 import { load, trackPageview } from 'fathom-client';
-import { useEffect } from 'react';
+import { useEffect, Suspense } from 'react';
 import { usePathname, useSearchParams } from 'next/navigation';
 
-export function Fathom() {
+function TrackPageView() {
   const pathname = usePathname();
   const searchParams = useSearchParams();
   useEffect(() => {
@@ -22,3 +22,11 @@ export function Fathom() {
 
   return null;
 }
+
+export default function Fathom() {
+  return (
+    <Suspense fallback={null}>
+      <TrackPageView />
+    </Suspense>
+  );
+}
```

---

Though I'm noticing a JSON error in Next when I curl the page using the new `<Suspense />` code.

I tried upgrading from `13.1.7-canary.10` to `13.1.7-canary.21`.

Both show this error in dev console:

In canary.21 it shows:

```
error - SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
```

In canary.10 it shows a bit more detail:

```
SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseModel (/Users/xxx/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:40:15)
    at resolveModule (/Users/xxx/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:665:24)
    at processFullRow (/Users/xxx/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:741:9)
    at processBinaryChunk (/Users/xxx/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:785:5)
    at progress (/Users/xxx/node_modules/next/dist/compiled/react-server-dom-webpack/client.js:839:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

(the `/Users/xxx` is just me removing some personal info)

**Comment by timneutkens** [comment]
Can you open an issue on the Next.js repo with a full reproduction, then we can take a look 👍

**Comment by briangershon** [comment]
Sounds good @timneutkens, I'll try to reproduce on a vanilla site, and will report back here.

**Comment by briangershon** [comment]
Please disregard, it was a problem on my end.

I pasted in the new Suspense code, but hadn't noticed the new code was using a default export; I had been using a named one.

So my fix was:

```diff
diff --git a/app/layout.tsx b/app/layout.tsx
index 1d3faaf..507c7a5 100644
--- a/app/layout.tsx
+++ b/app/layout.tsx
@@ -1,6 +1,6 @@
 import './globals.css';
 import { Navbar } from '@/components/Navbar';
-import { Fathom } from '@/components/Fathom';
+import Fathom from '@/components/Fathom';
```

Thanks again @timneutkens -- always a big Next.js fan -- and thanks @derrickreimer for your Fathom client! ☀️

**Comment by timneutkens** [comment]
Glad you figured it out!
