### ISSUE TITLE
Nextjs 13 App Dir example triggers twice on initial site load

### ISSUE THREAD

**Issue by IHIutch** [derrickreimer/fathom-client#45]
Just followed the guide on installing fathom using the App directory with Nextjs 13 and I noticed the `trackPageview()` runs twice on the initial site load. Basically, any initial visit or page refresh. 

<img width="432" alt="image" src="https://github.com/derrickreimer/fathom-client/assets/20825047/4e122538-4fa1-445e-85fa-6c04268bc6a7">

`next: 13.4.2`

Here's a repro: https://codesandbox.io/p/sandbox/inspiring-raman-yxnjxp

**Comment by derrickreimer** [comment]
Sorry for the trouble! This might be worth a shot. I suspect it's [auto-firing a page view on load](https://usefathom.com/docs/script/script-advanced#disable), and then firing another pageview in the other effect hook.

```diff
  function TrackPageView() {
    const pathname = usePathname()
    const searchParams = useSearchParams()

    useEffect(() => {
      load('MY_FATHOM_ID', {
        includedDomains: ['yourwebsite.com'],
+       auto: false
      })
    }, [])
```

Let me know if this solves it and we can update the docs!

**Comment by IHIutch** [comment]
Ah, yes that does appear to work. Thanks!

**Comment by derrickreimer** [comment]
Cool! I'll update the readme.

**Comment by shhgholipour** [comment]
> Sorry for the trouble! This might be worth a shot. I suspect it's [auto-firing a page view on load](https://usefathom.com/docs/script/script-advanced#disable), and then firing another pageview in the other effect hook.
> 
> ```diff
>   function TrackPageView() {
>     const pathname = usePathname()
>     const searchParams = useSearchParams()
> 
>     useEffect(() => {
>       load('MY_FATHOM_ID', {
>         includedDomains: ['yourwebsite.com'],
> +       auto: false
>       })
>     }, [])
> ```
> 
> Let me know if this solves it and we can update the docs!

It didn't work for me

**Comment by derrickreimer** [comment]
@shhgholipour do you have a Next.js repo you can point to that reproduces the issue?
