### ISSUE TITLE
Discussion: Adblockers and using a proxy for analytics

### ISSUE THREAD

**Issue by Innders** [derrickreimer/fathom-client#53]
Thank you for this awesome package!

We are currently testing both Fathom and Plausible for analytics tracking using Nextjs and Vercel.

Plausible makes it easy to setup a proxy to avoid being blocked by ad blockers. [Adblockers and using a proxy for analytics](https://plausible.io/docs/proxy/introduction). The client package even has this built in for [nextJs](https://github.com/4lejandrito/next-plausible#proxy-the-analytics-script).

I know this package is meant to be platform agnostic but this is an issue for all platforms.

Would you consider (if even possible) implementing features that let you set the path to the fathom script.
Script: `https://<yourdomain.com>/js/script.js -> https://cdn.usefathom.com/script.js`
Event: `https://<yourdomain.com>/api/event -> [I don't know the endpoint fathom users for events]`

Thanks for your time :)

**Comment by AshWills** [comment]
Hey @Innders,

Ash from Fathom 👋

Sorry that this reply is late, I just had a quick browse through the issues to see if there was anything I could answer and spotted your question. @prplecake is right that we deprecated custom domains back in May 2023. However, we are working on a reverse proxy solution that will enable you to bypass ad-blockers. We don't have an ETA for it's release at the moment, but work has begun on it, so we're absolutely committed to building it. Once it's built, we will definitely support an implementation with this awesome package/Next.js 🙂

**Comment by derrickreimer** [comment]
Nice @AshWills! Happy to roll support into this library once that's ready.

**Comment by Innders** [comment]
Thanks for getting back to me @AshWills! I read the blog post and it's totally understandable why you deprecated it.

From a business perspective it was a deal break for us unfortunately :( But I'm glad to hear that you are working on it again!

I think this discussion is closed now.
