### ISSUE TITLE
Fathom script loaded twice

### ISSUE THREAD

**Issue by bitstein** [derrickreimer/fathom-client#54]
I followed the instructions for adding this to app router. I see the script being loaded twice.

![image](https://github.com/derrickreimer/fathom-client/assets/4544062/72730763-0039-40ba-a648-2a4a5d27950e)

**Comment by derrickreimer** [comment]
I wonder if this is a React Strict Mode thing. Can you try disabling strict mode and see if this behavior stops? https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode

It's probably worth making our `load` function be a bit smarter about only injecting the script if it's not present on page already.

**Comment by bitstein** [comment]
> I wonder if this is a React Strict Mode thing. Can you try disabling strict mode and see if this behavior stops? https://nextjs.org/docs/pages/api-reference/next-config-js/reactStrictMode
> 
> It's probably worth making our `load` function be a bit smarter about only injecting the script if it's not present on page already.

@derrickreimer I can confirm that when I disabled strict mode, the script is only loaded once.

![Screenshot from 2024-03-11 09-43-18](https://github.com/derrickreimer/fathom-client/assets/4544062/7e530909-b220-4f7d-ae1f-0988bdb3f930)

**Comment by bitstein** [comment]
Thank you! I can confirm this is fixed on my production website.
